dist: xenial
language: python
python: 3.5
os: linux
env: TESTENV=py35-pyqt57

install:
  - bash scripts/dev/ci/install.sh "$TESTENV"
  - ulimit -c unlimited

script:
  - tox -e "$TESTENV"

after_failure:
  - bash scripts/dev/ci/travis_backtrace.sh
